/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thegaragelab_quickui_Driver */

#ifndef _Included_com_thegaragelab_quickui_Driver
#define _Included_com_thegaragelab_quickui_Driver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_thegaragelab_quickui_Driver
 * Method:    gfxInit
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_thegaragelab_quickui_Driver_gfxInit
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_thegaragelab_quickui_Driver
 * Method:    gfxBeginPaint
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_thegaragelab_quickui_Driver_gfxBeginPaint
  (JNIEnv *, jobject);

/*
 * Class:     com_thegaragelab_quickui_Driver
 * Method:    gfxEndPaint
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_thegaragelab_quickui_Driver_gfxEndPaint
  (JNIEnv *, jobject);

/*
 * Class:     com_thegaragelab_quickui_Driver
 * Method:    gfxSetClip
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_thegaragelab_quickui_Driver_gfxSetClip
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_thegaragelab_quickui_Driver
 * Method:    gfxPutPixel
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_thegaragelab_quickui_Driver_gfxPutPixel
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_thegaragelab_quickui_Driver
 * Method:    gfxFillRegion
 * Signature: (IIIII)I
 */
JNIEXPORT jint JNICALL Java_com_thegaragelab_quickui_Driver_gfxFillRegion
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_thegaragelab_quickui_Driver
 * Method:    gfxDrawImage
 * Signature: (II[BIIII[BI[B)I
 */
JNIEXPORT jint JNICALL Java_com_thegaragelab_quickui_Driver_gfxDrawImage
  (JNIEnv *, jobject, jint, jint, jbyteArray, jint, jint, jint, jint, jbyteArray, jint, jbyteArray);

/*
 * Class:     com_thegaragelab_quickui_Driver
 * Method:    gfxDrawLine
 * Signature: (IIIII)I
 */
JNIEXPORT jint JNICALL Java_com_thegaragelab_quickui_Driver_gfxDrawLine
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_thegaragelab_quickui_Driver
 * Method:    gfxDrawBox
 * Signature: (IIIII)I
 */
JNIEXPORT jint JNICALL Java_com_thegaragelab_quickui_Driver_gfxDrawBox
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_thegaragelab_quickui_Driver
 * Method:    gfxDrawChar
 * Signature: ([BIIIB)I
 */
JNIEXPORT jint JNICALL Java_com_thegaragelab_quickui_Driver_gfxDrawChar
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jbyte);

/*
 * Class:     com_thegaragelab_quickui_Driver
 * Method:    gfxDrawString
 * Signature: ([BIII[B)I
 */
JNIEXPORT jint JNICALL Java_com_thegaragelab_quickui_Driver_gfxDrawString
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jbyteArray);

/*
 * Class:     com_thegaragelab_quickui_Driver
 * Method:    gfxCheckEvents
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_thegaragelab_quickui_Driver_gfxCheckEvents
  (JNIEnv *, jobject);

/*
 * Class:     com_thegaragelab_quickui_Driver
 * Method:    gfxGetWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_thegaragelab_quickui_Driver_gfxGetWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_thegaragelab_quickui_Driver
 * Method:    gfxGetHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_thegaragelab_quickui_Driver_gfxGetHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_thegaragelab_quickui_Driver
 * Method:    gfxGetBufferSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_thegaragelab_quickui_Driver_gfxGetBufferSize
  (JNIEnv *, jobject);

/*
 * Class:     com_thegaragelab_quickui_Driver
 * Method:    gfxGetBuffer
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_thegaragelab_quickui_Driver_gfxGetBuffer
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
